### ISSUE TITLE
what is the default username/password ?

### ISSUE THREAD

**Issue by changchichung** [AlphaNecron/Chakram#16]
I cant' find anything about default login information in README or config files.
so what is the default username/password ? ??

**Comment by AlphaNecron** [comment]
Username: `admin`
Password: `voiduser`

**Comment by feskolech** [comment]
![image](https://user-images.githubusercontent.com/24978167/140899334-13929a54-0b0d-4620-b1b3-1885158d64b6.png)

admin:voiduser not working

**Comment by feskolech** [comment]
@AlphaNecron

**Comment by AlphaNecron** [comment]
`admin:voiduser` is the default credential. If you can't login, try `admin:draconicuser`

**Comment by feskolech** [comment]
@AlphaNecron > User not found

**Comment by AlphaNecron** [comment]
Are you using `docker`?

**Comment by feskolech** [comment]
no, direct install
![image](https://user-images.githubusercontent.com/24978167/140902472-a5eae883-4b8f-4a9b-bce0-4ff48a5fac48.png)

**Comment by AlphaNecron** [comment]
```bash
sudo -u postgres psql
\x
TABLE "User";
```
The output is the username.

**Comment by feskolech** [comment]
![image](https://user-images.githubusercontent.com/24978167/140902975-c55934af-9eaf-49d4-8c9a-2445768827cd.png)
lol nothing

**Comment by AlphaNecron** [comment]
Use `yarn prisma db seed` if you are using `yarn` or `npx prisma db seed` if you are using `npm`.

**Comment by changchichung** [comment]
```admin:voiduser``` or ```admin:draconicuser```  are both wrong .
![](https://i.imgur.com/OCAffNV.png)

![](https://i.imgur.com/4ih2MPB.png)

I'm using docker-compose, and here is the docker-compose.yml
I change the expose port only.
```
version: '3'
services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes: 
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  void:
    image: ghcr.io/alphanecron/void/void:v0
    ports:
      - '805:3000'
    restart: unless-stopped
    volumes:
      - './uploads:/void/uploads'
      - './public:/void/public'
      - './config.toml:/void/config.toml'
    depends_on:
      - 'postgres'
volumes:
  pg_data:
```
